### ISSUE TITLE
missing py.typed marker

### ISSUE THREAD

**Issue by phoenixr-codes** [magmax/python-readchar#100]
mypy raises an error when importing readchar.

```
error: Skipping analyzing "readchar": module is installed, but missing library stubs or py.typed marker
```

Fix this issue by adding a py.typed marker:

https://peps.python.org/pep-0561/#packaging-type-information

Python Version: 3.10.6
mypy version: 0.991
readchar version: 4.0.3

**Comment by Cube707** [comment]
is it enough to add the `py.typed` file, as the functions all provide typehints. Or would `*.pyi` files also be required?

**Comment by phoenixr-codes** [comment]
An empty `py.typed` file should be enough. No need to add extra type hints in seperate files.
