### ISSUE TITLE
Access to the pypi project

### ISSUE THREAD

**Issue by Cube707** [magmax/python-readchar#102]
@magmax can you grant me access to the pypi.org project, so that I can also handle problems there.

Alternatively can you jank the two pre-release versions for 4.0.4? They are useless, as the release-pipeline always releases master and doesn't work on branches currently

**Comment by magmax** [comment]
I already granted you access. Is it right?

**Comment by Cube707** [comment]
I am talking about this project: <https://pypi.org/project/readchar/>
You are right that you allready granted me acces to the github-repo here.


I would like to remove the releases `4.0.4.dev0` and `4.0.4.dev1` form pypi, as they are bad because of a bug in the release pipeline. (see https://github.com/magmax/python-readchar/pull/101#issuecomment-1459876966 and 4a69e22c8cc9bad50d942d32f359a35e5bc714ad)
You can do that for me or you can grant me acces to the pypi.org project as well so that I can handle it myself. Your decision.

**Comment by Cube707** [comment]
@magmax I just found the invite-email you send on friday in my SPAM folder. Sorry for that.

It is expired though, so could you please send another invite?
