### ISSUE TITLE
Different import conditions in `__init__.py` and `key.py`

### ISSUE THREAD

**Issue by pomponchik** [magmax/python-readchar#107]
Hello! I see in two places two different sets of OS, which one is correct?

https://github.com/magmax/python-readchar/blob/6ae17c235dc14c685f41e0827f565f555b3469e4/readchar/__init__.py#L11

https://github.com/magmax/python-readchar/blob/6ae17c235dc14c685f41e0827f565f555b3469e4/readchar/key.py#L8

**Comment by Cube707** [comment]
Good catch. This is a mistake. 

In generall MacOS and OpenBSD are only "tolerated" (see [README.md](README.md)). They will not throw errors as every unix system should work, but I do not offer active support for them. They will not be tested and issues for these operating systems will not be actively handeld.

**Comment by Cube707** [comment]
This probably came about, as the `key` file is just there for backwards compatibility. Its only relevant if someone uses `import readchar.key` instead of `from readchar import key` or `import readchar`.
