### ISSUE TITLE
Add some linters to the CI

### ISSUE THREAD

**Issue by pomponchik** [magmax/python-readchar#108]
Hello!

I see that you're using flake8, but i can't see it in the workflows. What about to add running some linters as a new workflow? And I suggest to use [Ruff](https://github.com/astral-sh/ruff) instead of flake8.

**Comment by Cube707** [comment]
What are the relevant upsides of `ruff`? `flake8` has not cased any issues up to this point, so why switch?

**Comment by pomponchik** [comment]
There is only one reason to use ruff - speed. You can save some time if you use it.

**Comment by Cube707** [comment]
with an empty cache `ruff` was only 50ms faster than `flask8` (on my machine), the project is simply to small to create really notable differences.

Doesn't justify moving away from tools that come from the official python team.

**Comment by pomponchik** [comment]
But what about adding any linters to the CI workflow?

**Comment by Cube707** [comment]
CI worklflow  runs `flake8` (any all other `pre-commit` steps).

So I don't get what you are suggesting
