### ISSUE TITLE
Use skipif decorator

### ISSUE THREAD

**Issue by pomponchik** [magmax/python-readchar#112]
Hello!

There is the [skipif](https://docs.pytest.org/en/latest/how-to/skipping.html#id1) decorator, you can use it to run tests intended only for your current OS. It is useful for using the OS matrix in the CI.

https://github.com/magmax/python-readchar/blob/6ae17c235dc14c685f41e0827f565f555b3469e4/tests/linux/test_readchar.py#L62

**Comment by Cube707** [comment]
know feature

but it is much easier to apply this to a whole folder instead of repeating boilerplate for every testcase:

https://github.com/magmax/python-readchar/blob/master/tests/linux/conftest.py#L10-L13
