### ISSUE TITLE
Wrong version metadata in the 4.2.0 release

### ISSUE THREAD

**Issue by ocefpaf** [magmax/python-readchar#122]
The latest 4.2.0 release reports itself as 4.1.1.dev0. See https://github.com/magmax/python-readchar/blob/d1d903d2d9ecae599fcb288b20c13e9593c9498d/pyproject.toml#L7

This breaks build tools that requires pip-check to ensure version consistency.

**Comment by Cube707** [comment]
the github has always reported a `*-dev` version and only the pypi releases get deployed with the full release-version, so this is not new.

But I am willing to work towards a solution for this

**Comment by ocefpaf** [comment]
> the github has always reported a `*-dev` version and only the pypi releases get deployed with the full release-version, so this is not new.

That is fine for the code that is on `main` but the released tarball, anywhere it lives, it would be nice to reflect the version of the taf.

> But I am willing to work towards a solution for this

I like [setuptools-scm](https://pypi.org/project/setuptools-scm/) for that. After setting it up, all you need to do is to tag a release.

**Comment by Cube707** [comment]
> I'd like to have a stable release in tagged versions, b/c this is by design, feel free to close it if you want

As users can install using `pip install git+https://github.com/magmax/python-readchar@v4.2.0` they should get the correct version displayed there, which is currently broken. so I will implement a fix in the coming days
