### ISSUE TITLE
running in multiprocess

### ISSUE THREAD

**Issue by MiriUll** [magmax/python-readchar#25]
Hey
I want to act when the END key is pressed. As I also want to act on a acpi event I need more loops. i wanted to do that with multiprocessing but when I start the key process I keep getting an error message "termios.error: (25, 'Inappropriate ioctl for device')".
I already hat a look at the other issue with that error message but that didn`t help me as without the process it works fine.

Thanks for your help :)

**Comment by suresttexas00** [comment]
Where are you running the command/program from?  That error is usually due to it not being a "real" terminal (such as during Pycharm interactive, etc..).  What terminal program and OS are you using?

**Comment by MiriUll** [comment]
I am running from yakuake on a Fedora 25 system.

**Comment by suresttexas00** [comment]
You should try a different terminal program or a tty session and see if the error is in those

**Comment by MiriUll** [comment]
I tried with the Konsole and still I get the same error :/

**Comment by suresttexas00** [comment]
how about tty (use alt-F1-6)?
