### ISSUE TITLE
PyPi version confusion

### ISSUE THREAD

**Issue by Codeberg-AsGithubAlternative-buhtz** [magmax/python-readchar#27]
I use Python3.6 on Windows 10. When I do ´pip install readchar` it collectes version ´0.7´.

But [PyPi](https://pypi.python.org/pypi/readchar) tells me that version `0.0.8` (not a typo!!) is the lates.

So what is going on here?

**Comment by calonx** [comment]
Check out [my reply](https://github.com/magmax/python-readchar/issues/26#issuecomment-349142134) to issue #26.

I suspect there was a simple mix-up with versioning, and that the right answer is for @magmax to do a version-bump to `0.10.0`.

**Comment by mbdevpl** [comment]
@magmax Please use consistent versioning, e.g. never decrease version number.

As can be seen here: https://pypi.org/project/readchar/#history

- 0.7 Sep 13, 2014 
- 0.1.0 Oct 23, 2017

This can only be fixed by using version higher than 0.7 (like 0.8.0 or 1.0.0) in the upcoming release. Version 0.1.0 is not higher than 0.7 -- because it is equivalent to 0.1!

Additionally, package information states that its "Development Status" is "5 - Production/Stable" so, for example according to semantic versioning, it should be at least at version 1.0.0 by now.

For now this can be worked around with `pip3.6 insatll readchar==0.1.0`, but still...

**Comment by danmichaelo** [comment]
There is a github tag for version 1.1.0, so I assume 0.1.0 is a typo for 1.1.0. But it would be very nice if a new version could be released to PyPI!

**Comment by mbdevpl** [comment]
@danmichaelo Unfortunately, The 1.1.0 tag was created on on 11 Jan 2015 -- so it's also very outdated. Version 0.1.0 is from 23 Oct 2017, so chronologically is by far latest. So I hope that 1.1.0 won't be released at all, and an actual fix is released instead ;)

**Comment by danmichaelo** [comment]
True, didn't see at first that there was also a version 0.0.8 and version 0.0.9 before 0.1.0. So yeah, best thing now would just be to have a version 0.8.0 I guess. @magmax, please reach out to the community if you need additional maintainers.

**Comment by mbdevpl** [comment]
@danmichaelo Exactly. @magmax I could help with maintaining readchar a bit (at least to push it back on the right track), if there are no other volunteers.

**Comment by magmax** [comment]
@danmichaelo @mbdevpl what do you need in order to do that?

I'm affraid I will be very busy until summer.

**Comment by mbdevpl** [comment]
@magmax Thanks! I'd need to have a `Maintainer` role for the `python-readchar` package on pypi.

So, if you'd login on https://pypi.python.org/ and then navigate to this address:

* https://pypi.python.org/pypi?:action=role_form&package_name=python-readchar

and finally add user `mbdev` as `Maintainer` -- my username on pypi is different than on GitHub. Then I could upload the new version myself.

**Comment by suresttexas00** [comment]
You may also wish to make danmichaelo a "Collaborator" here on Github.  He can then approve pull requests or other maintenance for you:
on the repo page:  Click the "settings" tab, on the left click the link for Collaborators.  You will be asked to verify your password.  After that you can search his name and add him...

**Comment by mbdevpl** [comment]
@suresttexas00 as of now, I can approve pull requests, but honestly IMHO there is nothing there to approve, yet. Most of them are even failing the tests, and the one that doesn't has a lot of comments by @magmax about code quality that were not yet addressed.

I'd gladly take a very long look at open issues and pull requests after the pypi version issue is resolved - all that remains is to 0.8.0 release that I've already tagged to be built and pushed to pypi. I'm waiting for the pypi permisisons on readchar package, then I can also do that myself :)

**Comment by danmichaelo** [comment]
@magmax Thanks for adding us! Hope you also have the chance to add mbdev as a PyPI maintainer per these instructions: https://github.com/magmax/python-readchar/issues/27#issuecomment-365515135 . Publishing a new release is the most pressing issue now.

**Comment by mbdevpl** [comment]
As versions 2.0.0 and then 2.0.1 have been released for quite some time, I think the version confusion has ended.
