### ISSUE TITLE
readchar() no longer working in 'linux' upon update to 1.0.0

### ISSUE THREAD

**Issue by brbsix** [magmax/python-readchar#3]
readchar.readchar() stopped working in all of my scripts upon updating to version 1.0.0. As it stands, it evaluates to `None`.

The issue seems to lie in readchar_linux.py's readchar() function. The following line evaluates to False:
    `if blocking or select.select([sys.stdin, ], [], [], 0.0)[0]:`

I'm not sure what `blocking` is for, but running readchar.readchar(True) or `os.read(sys.stdin.fileno(), 1)` will return a byte in Python 3.4.0, a str in Python 2.7.6.

I just ended up using a varation of the readchar_linux.py before the 2ea3d12a1f838405756f3ddda11d422cb4f23c08 commit on 1/8/15 and am getting the expected functionality.

**Comment by magmax** [comment]
The "blocking" parameter is to wait for an event to happen. If you didn't understood it, it is a bad name.

The idea is to return inmediatelly if no character is ready. This is to be able to get an alone ESC.

I think it was my fault by selecting the wrong default value: it should behave just as before. I will fix it in 1.1.0

**Comment by magmax** [comment]
Please, check version 1.1.0.

**Comment by brbsix** [comment]
Yes the default value of True is much better and allows everything to work as it did. Also the pesky os.read() returns bytes instead of str in Python 3 so I just submitted a pull request to ensure it still returns a str.

**Comment by suresttexas00** [comment]
'blocking' is a good name for this and is the name that one would expect for this parameter.  However, yes, it should be defaulting to True...
