### ISSUE TITLE
Support for Python 2.6 and 3.3 should be dropped

### ISSUE THREAD

**Issue by mbdevpl** [magmax/python-readchar#35]
Supporting outdated Python versions hinders development, because you have to worry about compatibility with obsolete and insecure software.

https://devguide.python.org/#status-of-python-branches

- 2.6: end-of-life 2013-10-29
- 3.3: end-of-life 2017-09-29

As can be seen above, 2.6 was put to rest more than 4 years ago, and 3.3 almost half a year ago. EOL means no updates -- even security updates. Using these Python versions is a really bad idea anyway, so why even test for them?

**Comment by mbdevpl** [comment]
As can be seen in link below there are some dependency errors when building `python-readchar` on these EOL versions.

https://travis-ci.org/mbdevpl/python-readchar/builds/339756231

**Comment by hugovk** [comment]
Python 2.6 and 3.3 are also little used. 

Here's the pip installs for readchar from PyPI for last month:

| python_version | percent | download_count |
| -------------- | ------: | -------------: |
| 2.7            |  74.32% |          2,191 |
| 3.6            |  19.40% |            572 |
| 3.5            |   5.39% |            159 |
| 3.4            |   0.81% |             24 |
| 2.6            |   0.07% |              2 |

Source: `pypinfo --start-date -40 --end-date -10 --percent --pip --markdown readchar pyversion`

**Comment by magmax** [comment]
Agree.
