### ISSUE TITLE
ctrl+c and ctrl+z (Linux) are intercepted

### ISSUE THREAD

**Issue by altendky** [magmax/python-readchar#40]
I suspect that while some people want to intercept ctrl+c and ctrl+z, many also do not want to.  I am no expert in this area so there may be significant issues with this but I figured I'd document the issue and share what I put together (along with another `#python` user).  This was written as a thing to use `readchar` but presumably could be translated into a feature for `readchar` proper.  No promises right now that I will get around to that.

https://repl.it/@altendky/readchar-getch-6
```python
import os
import signal
import sys

import readchar


signals = {
    '\x03': getattr(signal, 'SIGINT', getattr(signal, 'CTRL_C_EVENT', None)),
    '\x1a': getattr(signal, 'SIGTSTP', None),
}

kill = getattr(os, 'killpg', getattr(os, 'kill'))
pid = (
    os.tcgetpgrp(sys.stdin.fileno())
    if hasattr(os, 'tcgetpgrp')
    else os.getpid()
)


def prompt(text, options):
    prompt = '{} ({}): '.format(text, '/'.join(options))

    while True:
        sys.stdout.write(prompt)
        sys.stdout.flush()

        while True:
            answer = readchar.readchar()
            sig = signals.get(answer)

            if sig is not None:
                kill(pid, sig)
                continue
            
            break

        sys.stdout.write(answer + '\n')
        sys.stdout.flush()
        
        if answer in options:
            return answer


sys.stdout.write('answer: {}\n'.format(prompt('prompt', 'ynm')))
```

**Comment by rogerdahl** [comment]
This looks like it would work, but all that's really required is to change `tty.setraw()` to `tty.setcbreak()` in the library `readchar()` function. Since it's only a few lines, you can make a local copy of it:
```
def readchar():
    fd = sys.stdin.fileno()
    old_settings = termios.tcgetattr(fd)
    try:
        # tty.setraw(sys.stdin.fileno())
        tty.setcbreak(sys.stdin.fileno())
        ch = sys.stdin.read(1)
    finally:
        termios.tcsetattr(fd, termios.TCSADRAIN, old_settings)
    return ch
```

**Comment by shasheene** [comment]
I hit this same issue. Here's my workaround that may help people:

```
character = readchar.readchar()
# Note: readchar() currently intercepts CTRL-C etc [1]. The easiest solution is to
# detect CTRL-C and simply emit the relevant signal [2]
# [1] https://github.com/magmax/python-readchar/issues/40
# [2]
if character == '\x03':
    # Emit the relevant signal
    os.kill(os.getpid(), signal.SIGINT)
```

You can find [readchar's list of character codes here](https://github.com/magmax/python-readchar/blob/master/readchar/key.py).

I agree a better solution to modify the library to have an option, but this workaround is sufficient for my purposes right now.
