### ISSUE TITLE
Bad while loop pegging CPU on Windows

### ISSUE THREAD

**Issue by cdgriffith** [magmax/python-readchar#42]
https://github.com/magmax/python-readchar/blob/master/readchar/readchar.py#L71

Nothing slowing this while loop is causing a CPU core to be pegged on Windows. Either removing `if msvcrt.kbhit()` or adding a `time.sleep(0.001)` (or similar) is necessary.

**Comment by Cube707** [comment]
the new v4 under development in #79 should fix this problem, as it relyes on `msvcrt.getch()` to block untill the next keypress. This seems to be easier on the CPU.

For people needing it the option to run non-blocking is still there, but than the programmer would be responsible for implementing a `sleep()` to keep CPU usage managable.

**Comment by Cube707** [comment]
this should be fixed in `v4.0.0` as it no longer utilises a loop. can somebody confirm?
