### ISSUE TITLE
Create a GitHub release for version 2.0.1

### ISSUE THREAD

**Issue by mmahut** [magmax/python-readchar#45]
`pypi` is at 2.0.1, but `github` release at 2.0.0.

**Comment by agcopenhaver** [comment]
@magmax bump

**Comment by mwilson8** [comment]
@AuHau also wanted to bring this to your attention, as a listed maintainer on pypi

**Comment by rluria14** [comment]
@magmax bump. please make a release for 2.0.1 when you get a chance! thanks.
