### ISSUE TITLE
readkey does not work in PyCharm debugger

### ISSUE THREAD

**Issue by adlerzei** [magmax/python-readchar#51]
Hi,

I love your work but noticed that in PyCharm using the debugger the readkey function never returns anything. I am using Ubuntu 18.04 and PyCharm Community 2019.3.4. readchar is installed via pip in version 2.0.1. Do you know how I can fix it?

Cheerz

**Comment by lwanger** [comment]
Have you tried checking the box in the PyCharm debugger for terminal emulation (it is in the run configuration (see picture below). That has solved similar issues for me.

![Annotation 2020-03-30 110431](https://user-images.githubusercontent.com/923826/77934895-540bfa80-7276-11ea-85e4-55b2bf2e4452.jpg)
)?

**Comment by adlerzei** [comment]
Ah sorry for the late reply. Yes I already did that, without success. Do you have any other idea?

**Comment by lwanger** [comment]
Sorry, I don't except for trying the next option down to run with the Python Console. Unfortunately PyCharm likes to grab input when debugging. I had similar problems with working on my cooked_input package.

**Comment by adlerzei** [comment]
ok, thank you anyway! Anyone else having an idea?

**Comment by damc** [comment]
In my case, when I check that option, I don't have the error "termios..." and the program works but it halts on readkey function execution and even when I press key in the console, the program still is halting on readkey execution. Has anyone had that error and solved it?

**Comment by spuliaiev-sfdc** [comment]
I have been able to solve it by this fix: https://github.com/magmax/python-readchar/pull/70
