### ISSUE TITLE
Pls add support shift+tab

### ISSUE THREAD

**Issue by fleytman** [magmax/python-readchar#80]
I want use shift tab in inquirer. But readchar not read this keyevent
```
    print("Press a key")
    key = readchar.readkey()
    print("Key is {0}".format(key.encode()))
>>>Press a key
>>>shift+tab
>>>Key is b'\t'
```

**Comment by Cube707** [comment]
You didn't provide this crutial information, but from the fact that you only get a single `TAB` back, I assume you are on windows?

Windows doesn't modify the tab-key when pressing shift. So it is imposible to use `TAB+SHIFT` on windows, this has nothing to do with `readchar()` but is simpyl a windows limitation.

We could add it to the Linux side, but I would still not recomend using it as it is not portable...

**Comment by fleytman** [comment]
I'm use macos. It’s a pity that it won’t work for Windows, of course I want a cross-platform implementation. But support for *nix would also be nice.

**Comment by Cube707** [comment]
### For *nix support
This will have to wait but will probably come at some point. For now the project maintainer is not responding and untill he does I am just a powerless contributer myself. You can however patch the `key`-module for unix systems with this line after your `readchar` import:

```python
from readchar import readkey, key
key.SHIFT_TAB = "\x1b\x5b\x5a"
```

Now you can use it as expected:

```python
while True:
    k = readkey()
    if k == key.SHIFT_TAB:
        print("got macro shortcut!!!!!")
```


You can get the codes for other unsported keys by running [my testing script](https://github.com/Cube707/python-readchar/blob/dev-v4/tests/manual-test.py), it will print you the codes for all pressed keys.

### For windows support: 

`readchar` relies on the standart libary `msvcrt` to do the actuall terminal interaction. If you take this exapmple:

```python
from msvcrt import getch

while True:
	k = getch()
	print(k)
```
you will see that both pressing `TAB` and `SHIFT+TAB` result in the same output of `b'\t'`. Windows doesn't provide this keycombination to python so it is imposible to handle it.

**Comment by fleytman** [comment]
Thanks for your answer. I search why I can't use readchar.readkey(), it's https://github.com/magmax/python-readchar/issues/11 problem. Pycharm terminal != system terminal. In system macos term i can read shift+tab.

**Comment by fleytman** [comment]
It's work with inquirer https://github.com/magmax/python-inquirer/pull/170
