### ISSUE TITLE
Repository maintenance? (once again)

### ISSUE THREAD

**Issue by Cube707** [magmax/python-readchar#84]
@magmax @AuHau @mbdevpl 

The current version 3.0.5 is broken and has isses on both *nix and windows systems making it pretty unrelaiable. I provided soloutions and continued development and am now at a point I feel confident in saying the issues can and should be adresses.

If all of you are bussy or no longer intersed in maintaining this repository I would be happy to assist and help with getting this project back on its feet.

Alternativly I could fork the project and start a new package on PyPi, but I would like to not do that and have another package offering the same functionalaty.

looking forward to any form of feedback.

**Comment by mbdevpl** [comment]
I agree with your sentiments. I'm not so involved in the current development of the package although I've helped in the past and still use it (it's also a dependency of at least one package I'm maintaining myself), so it's puzzling to me that it is unusable to you.

With regards to rolling out fixes to the public, I think unfortunately @magmax is the only one who can publish new versions on pypi, so even if a fix is merged it can be a bottleneck. Which I fully understand given that the package is maintained on a volunteer basis, and I don't think any of the maintainers has capacity to test the package on all platforms.

I think if there are issues with the package, but those issues don't show up in CI builds, the highest impact contribution would be to add more tests that show those unexpected failures in CI, and then it would be much easier for any maintainer to judge and fix the package across affected platforms.

**Comment by Cube707** [comment]
"unusalble" was probably to harsh, but arrow/special key support is broken on windows and Backspace is broken on Linux, which I would both consider critical.

I didn't intend on coming across as "you need to inverst more time in this" and fully understand that this is voluntary, but I spend a considerable amount of time on providing fixes and improvments for this libary and would just like to now if there is hope they will be discussed in the near future.

> I think if there are issues with the package, but those issues don't show up in CI builds, the highest impact contribution would be to add more tests that show those unexpected failures in CI, and then it would be much easier for any maintainer to judge and fix the package across affected platforms.

And thats why I did exacly that :D (see #79)

**Comment by magmax** [comment]
do any of you want to be maintainers?  I could grant you perms if required.

**Comment by Cube707** [comment]
Yes, if it is ok with you I would be happy to maintain this repo.

**Comment by Cube707** [comment]
@magmax did you see my previous message? I would be happy to maintain this repo if you grant me permissions.
