### ISSUE TITLE
module 'readchar._posix_key' has no attribute 'ESCAPE_SEQUENCES'

### ISSUE THREAD

**Issue by Lovmong** [magmax/python-readchar#91]
warning in raspberry pi bullseye

**Comment by Cube707** [comment]
Please give the required information as described in [Contributing.md](https://github.com/magmax/python-readchar/blob/master/CONTRIBUTING.md#opening-an-issue)

I need to now:
- [ ] how are you using `readchar`? What code produces the error?
- Information about your system:
  - [x] your OS
  - [ ] your Python version and implementation (use `python --version`)
  - [ ] the version of readchar you use (use `pip show readchar`)

**Comment by Cube707** [comment]
Closing do to lack of information
