### ISSUE TITLE
Provide input prompt functionality

### ISSUE THREAD

**Issue by impredicative** [magmax/python-readchar#98]
It may make sense to provide an input prompt functionality.

For example, with Python `input`, I can do:

```python
input_str = input('Reading input: ')
```

This serves two purposes:
1. It shows the input prompt.
2. It echos the user input immediately on the same line. This is useful for clarity.

To get this with `readchar`, I would have to use something like:

```python
import readchar


def input_char(prompt: str, /, *, echo: bool = True) -> str:
    print(prompt, end='', flush=True)
    char = readchar.readchar()

    if echo:
        print(char)
    else:
        print()
    return char


def input_key(prompt: str, /, *, echo: bool = True) -> str:
    print(prompt, end='', flush=True)
    key = readchar.readkey()

    if echo:
        print(key)
    else:
        print()
    return key

# Usage:
char = input_char('Reading a char: ')
key = input_key('Reading a key: ')
```

**Comment by Cube707** [comment]
this is exactly provided by `input`, so why do you want it in `readchar`? 

`readchar` is mostly meant for usecase where you don't want this and need finer controll, so you would write the functions yourself anyway?

**Comment by Cube707** [comment]
`readchars` most common usecase is something like this:

```python
print("type a: ", end='')
while True:
    k = readchar()
    if k == 'a':
        break
    print(k, end='')
 
print("well done")
```

a input like function would re-prompt for every wrong input and is usually undesirable and the exact prosessing is specific to the usecase, so it cant be part of the libary.

So whats the usecase where this needs a prompt-function and it doesn't make more sens to prompt yourself, matcing your usecase

**Comment by Cube707** [comment]
I can defnetly see this usecase, but it is still quite special to you and not really something thats usefull inside the libary for a lot of people. You already have the function written, so just use it. Same for other users that will have slightly different requirement.

Also if you want your response so urgently, you will probably want to also implement a timeout. and than it becomes even more specific to your usecase...

**Comment by Cube707** [comment]
but if you want to code it up, feel free to implement a generic approach and send in a PR

**Comment by Cube707** [comment]
sidenote, you can shorten your function to this:

```python
def input_char(prompt: str, /, *, echo: bool = True) -> str:
    print(prompt, end='', flush=True)
    char = readchar.readchar()
    if echo:
        print(char)
    return char
```
